name: Github repos mirror from gitee periodic job

on:
  watch:
    types: started
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Gitee organization repos to Github.
      uses: falseen/hub-mirror-action@dev
      with:
        src: gitee/hanfubaike
        dst: github/hanfubaike
        dst_key: ${{ secrets.FALSEEN_PRIVATE_KEY}}
        dst_token:  ${{ secrets.GITHUBTOKEN }}
        account_type: org
        black_list: "hanfubaike"

    - name: Mirror the Gitee organization repos to Github.
      uses: wearerequired/git-mirror-action@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.FALSEEN_PRIVATE_KEY }}
      with:
        source-repo: 'git@gitee.com:hanfubaike/hanfubaike.git'
        destination-repo: 'git@github.com:hanfubaike/hanfubaike.github.io'
